server:
  port: 9102

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
spring:
  cloud:
    config:
      import-check:
        enabled: false