server:
  port: 9103

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orders-route
          uri: lb://infra-order
          predicates:
            - Path=/v1/orders/**

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9102/eureka/}

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG