spring:
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: '' # Empty password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: false # Disable Liquibase for the H2 profile
  kafka:
    consumer:
      group-id: inventory-service-group
  profiles:
    active: h2-local


# Topic Names
order:
  events:
    topic:
      created: order-created-events
      cancelled: order-cancelled-events
inventory:
  events:
    topic:
      reserved: inventory-reserved-events
      depleted: inventory-depleted-events

